<?php
/**
 * EvoRequestLinkRequest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * OpenAPI definition
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.6.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * EvoRequestLinkRequest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class EvoRequestLinkRequest implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'EvoRequestLinkRequest';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'apiToken' => 'string',
        'sessionID' => 'string',
        'languageKey' => 'string',
        'orderNumber' => 'string',
        'callbackPathSuccess' => 'string',
        'callbackPathFailure' => 'string',
        'callbackPathNotify' => 'string',
        'callbackPathBack' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'apiToken' => 'uuid',
        'sessionID' => null,
        'languageKey' => null,
        'orderNumber' => null,
        'callbackPathSuccess' => null,
        'callbackPathFailure' => null,
        'callbackPathNotify' => null,
        'callbackPathBack' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'apiToken' => false,
		'sessionID' => false,
		'languageKey' => false,
		'orderNumber' => false,
		'callbackPathSuccess' => false,
		'callbackPathFailure' => false,
		'callbackPathNotify' => false,
		'callbackPathBack' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'apiToken' => 'apiToken',
        'sessionID' => 'sessionID',
        'languageKey' => 'languageKey',
        'orderNumber' => 'orderNumber',
        'callbackPathSuccess' => 'callbackPathSuccess',
        'callbackPathFailure' => 'callbackPathFailure',
        'callbackPathNotify' => 'callbackPathNotify',
        'callbackPathBack' => 'callbackPathBack'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'apiToken' => 'setApiToken',
        'sessionID' => 'setSessionID',
        'languageKey' => 'setLanguageKey',
        'orderNumber' => 'setOrderNumber',
        'callbackPathSuccess' => 'setCallbackPathSuccess',
        'callbackPathFailure' => 'setCallbackPathFailure',
        'callbackPathNotify' => 'setCallbackPathNotify',
        'callbackPathBack' => 'setCallbackPathBack'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'apiToken' => 'getApiToken',
        'sessionID' => 'getSessionID',
        'languageKey' => 'getLanguageKey',
        'orderNumber' => 'getOrderNumber',
        'callbackPathSuccess' => 'getCallbackPathSuccess',
        'callbackPathFailure' => 'getCallbackPathFailure',
        'callbackPathNotify' => 'getCallbackPathNotify',
        'callbackPathBack' => 'getCallbackPathBack'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('apiToken', $data ?? [], null);
        $this->setIfExists('sessionID', $data ?? [], null);
        $this->setIfExists('languageKey', $data ?? [], null);
        $this->setIfExists('orderNumber', $data ?? [], null);
        $this->setIfExists('callbackPathSuccess', $data ?? [], null);
        $this->setIfExists('callbackPathFailure', $data ?? [], null);
        $this->setIfExists('callbackPathNotify', $data ?? [], null);
        $this->setIfExists('callbackPathBack', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets apiToken
     *
     * @return string|null
     */
    public function getApiToken()
    {
        return $this->container['apiToken'];
    }

    /**
     * Sets apiToken
     *
     * @param string|null $apiToken A token, which should be used as a security login
     *
     * @return self
     */
    public function setApiToken($apiToken)
    {
        if (is_null($apiToken)) {
            throw new \InvalidArgumentException('non-nullable apiToken cannot be null');
        }
        $this->container['apiToken'] = $apiToken;

        return $this;
    }

    /**
     * Gets sessionID
     *
     * @return string|null
     */
    public function getSessionID()
    {
        return $this->container['sessionID'];
    }

    /**
     * Sets sessionID
     *
     * @param string|null $sessionID ID of the Websession
     *
     * @return self
     */
    public function setSessionID($sessionID)
    {
        if (is_null($sessionID)) {
            throw new \InvalidArgumentException('non-nullable sessionID cannot be null');
        }
        $this->container['sessionID'] = $sessionID;

        return $this;
    }

    /**
     * Gets languageKey
     *
     * @return string|null
     */
    public function getLanguageKey()
    {
        return $this->container['languageKey'];
    }

    /**
     * Sets languageKey
     *
     * @param string|null $languageKey Language
     *
     * @return self
     */
    public function setLanguageKey($languageKey)
    {
        if (is_null($languageKey)) {
            throw new \InvalidArgumentException('non-nullable languageKey cannot be null');
        }
        $this->container['languageKey'] = $languageKey;

        return $this;
    }

    /**
     * Gets orderNumber
     *
     * @return string|null
     */
    public function getOrderNumber()
    {
        return $this->container['orderNumber'];
    }

    /**
     * Sets orderNumber
     *
     * @param string|null $orderNumber Order number for the current process for the client
     *
     * @return self
     */
    public function setOrderNumber($orderNumber)
    {
        if (is_null($orderNumber)) {
            throw new \InvalidArgumentException('non-nullable orderNumber cannot be null');
        }
        $this->container['orderNumber'] = $orderNumber;

        return $this;
    }

    /**
     * Gets callbackPathSuccess
     *
     * @return string|null
     */
    public function getCallbackPathSuccess()
    {
        return $this->container['callbackPathSuccess'];
    }

    /**
     * Sets callbackPathSuccess
     *
     * @param string|null $callbackPathSuccess Callback path success
     *
     * @return self
     */
    public function setCallbackPathSuccess($callbackPathSuccess)
    {
        if (is_null($callbackPathSuccess)) {
            throw new \InvalidArgumentException('non-nullable callbackPathSuccess cannot be null');
        }
        $this->container['callbackPathSuccess'] = $callbackPathSuccess;

        return $this;
    }

    /**
     * Gets callbackPathFailure
     *
     * @return string|null
     */
    public function getCallbackPathFailure()
    {
        return $this->container['callbackPathFailure'];
    }

    /**
     * Sets callbackPathFailure
     *
     * @param string|null $callbackPathFailure Callback path failure
     *
     * @return self
     */
    public function setCallbackPathFailure($callbackPathFailure)
    {
        if (is_null($callbackPathFailure)) {
            throw new \InvalidArgumentException('non-nullable callbackPathFailure cannot be null');
        }
        $this->container['callbackPathFailure'] = $callbackPathFailure;

        return $this;
    }

    /**
     * Gets callbackPathNotify
     *
     * @return string|null
     */
    public function getCallbackPathNotify()
    {
        return $this->container['callbackPathNotify'];
    }

    /**
     * Sets callbackPathNotify
     *
     * @param string|null $callbackPathNotify Callback path notify
     *
     * @return self
     */
    public function setCallbackPathNotify($callbackPathNotify)
    {
        if (is_null($callbackPathNotify)) {
            throw new \InvalidArgumentException('non-nullable callbackPathNotify cannot be null');
        }
        $this->container['callbackPathNotify'] = $callbackPathNotify;

        return $this;
    }

    /**
     * Gets callbackPathBack
     *
     * @return string|null
     */
    public function getCallbackPathBack()
    {
        return $this->container['callbackPathBack'];
    }

    /**
     * Sets callbackPathBack
     *
     * @param string|null $callbackPathBack Callback path back
     *
     * @return self
     */
    public function setCallbackPathBack($callbackPathBack)
    {
        if (is_null($callbackPathBack)) {
            throw new \InvalidArgumentException('non-nullable callbackPathBack cannot be null');
        }
        $this->container['callbackPathBack'] = $callbackPathBack;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


