<?php
/**
 * PartnerLeiData
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * OpenAPI definition
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.6.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * PartnerLeiData Class Doc Comment
 *
 * @category Class
 * @description All company data to create the LEI
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class PartnerLeiData implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'PartnerLeiData';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'legal_address_data' => '\OpenAPI\Client\Model\AddressData',
        'hq_address_data' => '\OpenAPI\Client\Model\AddressData',
        'entity_data' => '\OpenAPI\Client\Model\EntityData',
        'relationship_data' => '\OpenAPI\Client\Model\RelationshipData',
        'auth_person' => 'string[]',
        'contact_address' => '\OpenAPI\Client\Model\ContactAddress'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'legal_address_data' => null,
        'hq_address_data' => null,
        'entity_data' => null,
        'relationship_data' => null,
        'auth_person' => null,
        'contact_address' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'legal_address_data' => false,
		'hq_address_data' => false,
		'entity_data' => false,
		'relationship_data' => false,
		'auth_person' => false,
		'contact_address' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'legal_address_data' => 'legalAddressData',
        'hq_address_data' => 'hqAddressData',
        'entity_data' => 'entityData',
        'relationship_data' => 'relationshipData',
        'auth_person' => 'authPerson',
        'contact_address' => 'contactAddress'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'legal_address_data' => 'setLegalAddressData',
        'hq_address_data' => 'setHqAddressData',
        'entity_data' => 'setEntityData',
        'relationship_data' => 'setRelationshipData',
        'auth_person' => 'setAuthPerson',
        'contact_address' => 'setContactAddress'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'legal_address_data' => 'getLegalAddressData',
        'hq_address_data' => 'getHqAddressData',
        'entity_data' => 'getEntityData',
        'relationship_data' => 'getRelationshipData',
        'auth_person' => 'getAuthPerson',
        'contact_address' => 'getContactAddress'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('legal_address_data', $data ?? [], null);
        $this->setIfExists('hq_address_data', $data ?? [], null);
        $this->setIfExists('entity_data', $data ?? [], null);
        $this->setIfExists('relationship_data', $data ?? [], null);
        $this->setIfExists('auth_person', $data ?? [], null);
        $this->setIfExists('contact_address', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets legal_address_data
     *
     * @return \OpenAPI\Client\Model\AddressData|null
     */
    public function getLegalAddressData()
    {
        return $this->container['legal_address_data'];
    }

    /**
     * Sets legal_address_data
     *
     * @param \OpenAPI\Client\Model\AddressData|null $legal_address_data legal_address_data
     *
     * @return self
     */
    public function setLegalAddressData($legal_address_data)
    {
        if (is_null($legal_address_data)) {
            throw new \InvalidArgumentException('non-nullable legal_address_data cannot be null');
        }
        $this->container['legal_address_data'] = $legal_address_data;

        return $this;
    }

    /**
     * Gets hq_address_data
     *
     * @return \OpenAPI\Client\Model\AddressData|null
     */
    public function getHqAddressData()
    {
        return $this->container['hq_address_data'];
    }

    /**
     * Sets hq_address_data
     *
     * @param \OpenAPI\Client\Model\AddressData|null $hq_address_data hq_address_data
     *
     * @return self
     */
    public function setHqAddressData($hq_address_data)
    {
        if (is_null($hq_address_data)) {
            throw new \InvalidArgumentException('non-nullable hq_address_data cannot be null');
        }
        $this->container['hq_address_data'] = $hq_address_data;

        return $this;
    }

    /**
     * Gets entity_data
     *
     * @return \OpenAPI\Client\Model\EntityData|null
     */
    public function getEntityData()
    {
        return $this->container['entity_data'];
    }

    /**
     * Sets entity_data
     *
     * @param \OpenAPI\Client\Model\EntityData|null $entity_data entity_data
     *
     * @return self
     */
    public function setEntityData($entity_data)
    {
        if (is_null($entity_data)) {
            throw new \InvalidArgumentException('non-nullable entity_data cannot be null');
        }
        $this->container['entity_data'] = $entity_data;

        return $this;
    }

    /**
     * Gets relationship_data
     *
     * @return \OpenAPI\Client\Model\RelationshipData|null
     */
    public function getRelationshipData()
    {
        return $this->container['relationship_data'];
    }

    /**
     * Sets relationship_data
     *
     * @param \OpenAPI\Client\Model\RelationshipData|null $relationship_data relationship_data
     *
     * @return self
     */
    public function setRelationshipData($relationship_data)
    {
        if (is_null($relationship_data)) {
            throw new \InvalidArgumentException('non-nullable relationship_data cannot be null');
        }
        $this->container['relationship_data'] = $relationship_data;

        return $this;
    }

    /**
     * Gets auth_person
     *
     * @return string[]|null
     */
    public function getAuthPerson()
    {
        return $this->container['auth_person'];
    }

    /**
     * Sets auth_person
     *
     * @param string[]|null $auth_person auth_person
     *
     * @return self
     */
    public function setAuthPerson($auth_person)
    {
        if (is_null($auth_person)) {
            throw new \InvalidArgumentException('non-nullable auth_person cannot be null');
        }
        $this->container['auth_person'] = $auth_person;

        return $this;
    }

    /**
     * Gets contact_address
     *
     * @return \OpenAPI\Client\Model\ContactAddress|null
     */
    public function getContactAddress()
    {
        return $this->container['contact_address'];
    }

    /**
     * Sets contact_address
     *
     * @param \OpenAPI\Client\Model\ContactAddress|null $contact_address contact_address
     *
     * @return self
     */
    public function setContactAddress($contact_address)
    {
        if (is_null($contact_address)) {
            throw new \InvalidArgumentException('non-nullable contact_address cannot be null');
        }
        $this->container['contact_address'] = $contact_address;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


